server:
  port: 8115

spring:
  application:
    name: trade-receiver
  profiles:
    active: dev
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.mtx.trade.receiver.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl #org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

global-id:
  enabled: true
  snowflake:
    datacenter-id: 1
    worker-id: 1
    max-clock-backward-ms: 5
  domains:
    - order
    - payment

trade:
  storage:
    local:
      enabled: true
      sql-show: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.mtx.trade: debug
    org.springframework.web: info
