server:
  port: 8083
  servlet:
    context-path: /trade-pipeline

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/trade_pipeline_fake?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password:
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      connection-timeout: 30000
  data:
    redis:
      host: localhost
      port: 6379
      password: 87654321
      database: 5
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 32
          max-idle: 16
          min-idle: 4

logging:
  level:
    com.mtx.trade: info
    org.springframework.web: info

trade:
  storage:
    local:
      sql-show: false
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/trade_flow_fake?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      username: root
      password:
      hikari:
        maximum-pool-size: 50
        minimum-idle: 10
        connection-timeout: 30000
        read-only: true
